### PR TITLE
fix(autoscaling): set min nodes to 1 in order to allow the autoscaler to consider the machineset for autoscaling

### PR DESCRIPTION
**Pull request by machi1990**
## Description

Set min nodes to 1 in order to allow the autoscaler to consider the machineset for autoscaling
Depending on wether we are multi_az or single_az, the ocm provider will perform the round up to the multiple of 3

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Review by VanillaSpoon — APPROVED** [review]
Lgtm :) thanks @machi1990

**Comment by machi1990** [comment]
Thank you @VanillaSpoon

**Comment by miguelsorianod** [comment]
> Set min nodes to 1 in order to allow the autoscaler to consider the machineset for autoscaling

Can you expand a little bit on this?

**Comment by machi1990** [comment]
> > Set min nodes to 1 in order to allow the autoscaler to consider the machineset for autoscaling
> 
> Can you expand a little bit on this?

There has to be at least one replica in the node group (machine set) for cluster autoscaler to trigger scaling up behaviour on that node group. Otherwise, no scaling is going to be triggered and a bunch of warnings are shown.

Hive should be able to determine this for us and set this up for us as per https://github.com/openshift/hive/commit/30db34d2940a11e1e9a173a570fc5a09e31a1ccb but it appears that it is not working as it should.

**Pull request merged**
