### PR TITLE
doc: add GCP configuration documentation in README.md

### PR DESCRIPTION
**Pull request by miguelsorianod**
## Description

Add documentation on how to configure KFM to be able to deploy data plane clusters located in GCP.

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Comment by miguelsorianod** [comment]
I added the do not merge label to this PR as we shouldn't merge this as we consider GCP as "enabled" / ready to be used.

However, this PR can be reviewed already

**Comment by miguelsorianod** [comment]
Specifics about how to retrieve our environment specific credentials for development have not been added in this repository/documentatior. For that refer to our team onboarding documentation.

**Review by pawelpaszki — COMMENTED** [review]
the content here seems reasonable. I haven't used gcp for osd clusters creation yet, so I will let others that did take a look as well. just small question - the name of the role `osd-ccs-admin` is different than in AWS, can you confirm?

**Comment by miguelsorianod** [comment]
I am also working on adding a makefile target to setup credentials

**Comment by miguelsorianod** [comment]
I added the new Makefile target and updated the documentation.

This should be ready for review

**Review by pawelpaszki — APPROVED** [review]

**Comment by vmanley** [comment]
LGTM. Content clear and well linked

**Comment by machi1990** [comment]
> I added the do not merge label to this PR as we shouldn't merge this as we consider GCP as "enabled" / ready to be used.

@miguelsorianod the PR still awaits for GCP evaluation?

**Comment by miguelsorianod** [comment]
> > I added the do not merge label to this PR as we shouldn't merge this as we consider GCP as "enabled" / ready to be used.
> 
> @miguelsorianod the PR still awaits for GCP evaluation?

Yes.

**Review by pb82 — APPROVED** [review]

**Pull request merged**
