### PR TITLE
feat: added array utilities

### PR DESCRIPTION
**Pull request by ziccardi**
## Description
Added the following array utilities:

- **func FindFirst(predicate func(x interface{}) bool, values ...interface{}) (int, interface{})**: find the first occurrence matching the passed in predicate into the list of received values. Won't be needed anymore when we will have _generics_.
This function accepts a `...interface{}` instead of an `[]interface{}` because this way it can be used seamlessly with strings, int, int64, objects, etc. The drawbacks are:
    - the values are converted to a []interface
    - returned value is an interface{}
- **func FindFirstString(values []string, predicate func(x string) bool) (int, string)**: returns the index of the first string matching the passed in predicate and the string itself. `-1` and empty string if not found
- **func FilterStringSlice(values []string, predicate func(x string) bool) []string**: returns a slice of all the string into the passed in array matching the given predicate
- **func FirstNonEmpty(values ...string) (string, error)**: returns the first non empty string between the passed in values. If not found returns an error and the empty string
- **func FirstNonEmptyOrDefault(defaultValue string, values ...string) string**: returns the first non empty string between the passed in values. If not found returns `defaultValue`

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has created for changes required on the client side

### CODE REVIEW

**Review by machi1990 — COMMENTED** [review]
It will be good to use some of these in some places in the codebase e.g the parts discussed in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/813#discussion_r832075772, wdyt?

**Comment by ziccardi** [comment]
> It will be good to use some of these in some places in the codebase e.g the parts discussed in [#813 (comment)](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/813#discussion_r832075772), wdyt?

Yes, but I was thinking about another PR for that. Do you think I should add some here as an example usage?

**Comment by machi1990** [comment]
> > It will be good to use some of these in some places in the codebase e.g the parts discussed in [#813 (comment)](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/813#discussion_r832075772), wdyt?
> 
> Yes, but I was thinking about another PR for that. Do you think I should add some here as an example usage?

Yes. I think having some will be good. But if you have another PR lined up for this as well, that's also perfect. Thank you so much, this is really great work.

**Comment by ziccardi** [comment]
> Yes. I think having some will be good. But if you have another PR lined up for this as well, that's also perfect. Thank you so much, this is really great work.

Added a commit with some code refactored using the new utility function

**Review by machi1990 — APPROVED** [review]
thanks @ziccardi 

lgtm.

The docs will be added afterwards, correct?

**Pull request merged**
