### PR TITLE
chore: ignore test folders from coverage report

### PR DESCRIPTION
**Pull request by machi1990**
## Description

integration test folders have to be ignored from the coverage report. They are currently not ignored and it leads to comments like https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1353#issuecomment-1285373016

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Review by pawelpaszki — APPROVED** [review]

**Comment by miguelsorianod** [comment]
Shouldn't connector integration tests be ignored too then?

**Comment by miguelsorianod** [comment]
I understand the motivation is that the coverage should be only about code coverage from unit tests.
Can we update the descriptions in the Makefile help descriptions to make it more explicit?

**Comment by machi1990** [comment]
> Shouldn't connector integration tests be ignored too then?

They are already ignored https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/6a67e091a0a734115d516c78b9fe10e252b1e6e8/Makefile#L327

**Comment by machi1990** [comment]
> I understand the motivation is that the coverage should be only about code coverage from unit tests. Can we update the descriptions in the Makefile help descriptions to make it more explicit?

We could. Do you have a description in mind? (/me looking for suggestions here)

**Comment by miguelsorianod** [comment]
> We could. Do you have a description in mind? (/me looking for suggestions here)

Yes. Instead of telling that we generate test coverage report we can say we generate unit tests coverage report

**Pull request merged**
