### PR TITLE
refactor(scripts): remove unused realm config files

### PR DESCRIPTION
**Pull request by machi1990**
## Description

Follows up on https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/840 wherewe decided to configure the realms using a script which does not use these files

/cc @akoserwal I'd like your opinion on this, I noticed these files and I thought they could be removed since they are not used. 

## Verification Steps

1. CI passing
2. Confirmation from @akoserwal that they the files can be removed

## Checklist (Definition of Done)

- ~~[ ] All acceptance criteria specified in JIRA have been completed~~
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- ~~[ ] Documentation added for the feature~~
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- ~~[ ] Required metrics/dashboards/alerts have been added (or PR created).~~
- ~~[ ] Required Standard Operating Procedure (SOP) is added.~~
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@machi1990 just FYI, I'm currently trying to create a kustomize profile to easily set up a cos-fleet-manager especially for   developer purpose (ui, fleet shard) that do not require to checkout the fleet manager repo and what not.

The set up relies on exported realms from keycloak instamve as you can see here https://github.com/lburgazzoli/bf2-cos-fleet-manager/tree/kustomize/kustomize/overlays/local/keycloak and that makes the set up of keycloak 18 really easy.

**Comment by machi1990** [comment]
> @machi1990 just FYI, I'm currently trying to create a kustomize profile to easily set up a cos-fleet-manager especially for developer purpose (ui, fleet shard) that do not require to checkout the fleet manager repo and what not.

Is this is more like cost-installer? see [kas-installer](https://github.com/bf2fc6cc711aee1a0c2a/kas-installer) for reference of the name. 
  
> The set up relies on exported realms from keycloak instamve as you can see here https://github.com/lburgazzoli/bf2-cos-fleet-manager/tree/kustomize/kustomize/overlays/local/keycloak and that makes the set up of keycloak 18 really easy.

Thanks, that is indeed good info to know.  I can see that you have realm config in https://github.com/lburgazzoli/bf2-cos-fleet-manager/blob/kustomize/kustomize/overlays/local/keycloak/data, is this folder somehow copied / being pulled from kas-fleet-manager repo at the moment and thus we should keep the realm config that are being removed?

**Comment by lburgazzoli** [comment]
> > @machi1990 just FYI, I'm currently trying to create a kustomize profile to easily set up a cos-fleet-manager especially for developer purpose (ui, fleet shard) that do not require to checkout the fleet manager repo and what not.
> 
> 
> 
> Is this is more like cost-installer? see [kas-installer](https://github.com/bf2fc6cc711aee1a0c2a/kas-installer) for reference of the name. 
> 

It relates but it is not meant to be exactly the same as kas-installer

>   
> 
> > The set up relies on exported realms from keycloak instamve as you can see here https://github.com/lburgazzoli/bf2-cos-fleet-manager/tree/kustomize/kustomize/overlays/local/keycloak and that makes the set up of keycloak 18 really easy.
> 
> 
> 
> Thanks, that is indeed good info to know.  I can see that you have realm config in https://github.com/lburgazzoli/bf2-cos-fleet-manager/blob/kustomize/kustomize/overlays/local/keycloak/data, is this folder somehow copied / being pulled from kas-fleet-manager repo at the moment and thus we should keep the realm config that are being removed?

The files I have are the result of running the keycloak setup/config script and them exporting the realms so I don't know if they are exactly the same (didn't check). However with keycloak 18 it is very easy to import them and have a running instance which make it easy to set up a local instance in a single step instead of a sequence of commands (not a big deal of course, just to make you aware)

**Comment by machi1990** [comment]
> > > @machi1990 just FYI, I'm currently trying to create a kustomize profile to easily set up a cos-fleet-manager especially for developer purpose (ui, fleet shard) that do not require to checkout the fleet manager repo and what not.
> > 
> > 
> > Is this is more like cost-installer? see [kas-installer](https://github.com/bf2fc6cc711aee1a0c2a/kas-installer) for reference of the name.
> 
> It relates but it is not meant to be exactly the same as kas-installer
> 
> > > The set up relies on exported realms from keycloak instamve as you can see here https://github.com/lburgazzoli/bf2-cos-fleet-manager/tree/kustomize/kustomize/overlays/local/keycloak and that makes the set up of keycloak 18 really easy.
> > 
> > 
> > Thanks, that is indeed good info to know.  I can see that you have realm config in https://github.com/lburgazzoli/bf2-cos-fleet-manager/blob/kustomize/kustomize/overlays/local/keycloak/data, is this folder somehow copied / being pulled from kas-fleet-manager repo at the moment and thus we should keep the realm config that are being removed?
> 
> The files I have are the result of running the keycloak setup/config script and them exporting the realms so I don't know if they are exactly the same (didn't check). However with keycloak 18 it is very easy to import them and have a running instance which make it easy to set up a local instance in a single step instead of a sequence of commands (not a big deal of course, just to make you aware)

Right. One of the challenge we had with using something like https://github.com/lburgazzoli/bf2-cos-fleet-manager/blob/kustomize/kustomize/overlays/local/keycloak/run.sh#L8 is because in CI the keycloak service https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/0cf2f5723b04ee57b3540a473640f1bda37a8b6b/.github/workflows/ci.yaml#L87 is setup before code checkout happens https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/0cf2f5723b04ee57b3540a473640f1bda37a8b6b/.github/workflows/ci.yaml#L106. The import files are then not available for them to be given to the keycloak docker container at the time of keycloak service initialisation. That's why we went with the script option for configuration. 
An alternative would have been the CI to run the keycloak container via a script which we didnt pursue cause of concerns in dealing with container cleanup. Does keycloak 18 provide a Rest API to import realm all config at once?

**Comment by lburgazzoli** [comment]
> > 
> > The files I have are the result of running the keycloak setup/config script and them exporting the realms so I don't know if they are exactly the same (didn't check). However with keycloak 18 it is very easy to import them and have a running instance which make it easy to set up a local instance in a single step instead of a sequence of commands (not a big deal of course, just to make you aware)
> 
> Right. One of the challenge we had with using something like [https://github.com/lburgazzoli/bf2-cos-fleet-manager
> is setup before code checkout happens
> . The import files are then not available for them to be given to the keycloak docker container at the time of keycloak service initialisation. That's why we went with the script option for configuration.

I perfectly understand that so I have no objection to remove the files from the repo, my goal was just to mention that may be very convenient to have such files or to have a keycloak base image that is already set-up for local testing.

> An alternative would have been the CI to run the keycloak container via a script which we didnt pursue cause of concerns in dealing with container cleanup. Does keycloak 18 provide a Rest API to import realm all config at once?

This is something I have not explored to be honest.

**Comment by akoserwal** [comment]
I think we should keep them.

**Pull request closed without merging**
