### PR TITLE
fix: remove size limit

### PR DESCRIPTION
**Pull request by akoserwal**
Removing size limit check

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Review by JameelB — COMMENTED** [review]
@akoserwal this doesn't return a bad request anymore if it's 0 with rhsso client?

**Comment by akoserwal** [comment]
@JameelB I'll create a jira to test it with rhsso client & testing. I think is it creating an issue with the listing service account.

**Review by JameelB — APPROVED** [review]
approving since we're not using rhsso client just yet.

**Comment by ziccardi** [comment]
> @JameelB I'll create a jira to test it with rhsso client & testing. I think is it creating an issue with the listing service account.

I don't think it is related. The keycloak_service (massso) is using the `GetClients` method that returns the max allowed number of clients when max is 0: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/398f0d1a50be9b58f83c4740064c5799f3a921ff/pkg/services/sso/keycloak_service.go#L228

Doc: https://pkg.go.dev/github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/client/keycloak#KcClient.GetClients

The fix is correct but, IMO, should be put here: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/3693437afa71e729154a76fd4fa26f28592b4a36/pkg/client/redhatsso/client.go#L147 to have in redhatsso the same behaviour we had previously with massso.

**Pull request closed without merging**
