### PR TITLE
feat: update minimum required Go version to 1.19.0

### PR DESCRIPTION
**Pull request by miguelsorianod**
## Description

This PR updates the minimum required go version for KFM to 1.19.0. Go 1.17 is not supported anymore.

Changes:
* Update moq version
* Update golangci-lint version (and its corresponding GitHub action)
* Stop using `ioutil` in non-generated code as it is deprecated
* Fix missing autogeneration of some moq files
* Update different container image building files to use Go 1.19.0
* Stop using `-d` flag in `go get`as it is the default behavior now
* Updated minimum Go version requirements in README.md
* Update go.mod `go` directive to go 1.19

## Verification Steps
* Verify kas fleet manager can be built
* Verify `make generate` runs successfully
* Verify `make lint` runs successfully
* Verify `make verify` runs successfully
* Tests pass

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Comment by miguelsorianod** [comment]
cc @valdar @dhirajsb @lburgazzoli as this affects connectors code too

**Comment by miguelsorianod** [comment]
cc @valdar @dhirajsb @lburgazzoli it seems some connector test/s are failing. Could you check why?

Thanks

**Comment by miguelsorianod** [comment]
> cc @valdar @dhirajsb @lburgazzoli it seems some connector test/s are failing in this PR. Could you check why?
> 
> Thanks

If it helps, the connector tests that are failing are:

```
--- Failed steps:

  Scenario: Cannot create eval namespace with no ready eval clusters # features/connector-multitenancy-api.feature:49
    Then the response code should be 202 # features/connector-multitenancy-api.feature:82
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7m4902vuqsou1rg due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7m4902vuqsou1r0","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7m4902vuqsou1rg due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7m4902vuqsou1r0","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}


  Scenario Outline: Create eval namespace # features/connector-multitenancy-api.feature:132
    Then the response code should be 202 # features/connector-multitenancy-api.feature:140
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou16g due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou110","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou16g due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou110","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}


  Scenario Outline: Create eval namespace # features/connector-multitenancy-api.feature:132
    Then the response code should be 202 # features/connector-multitenancy-api.feature:140
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou0v0 due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0rg","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou0v0 due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0rg","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}


  Scenario Outline: Create eval namespace # features/connector-multitenancy-api.feature:132
    Then the response code should be 202 # features/connector-multitenancy-api.feature:140
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou15g due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0u0","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou15g due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0u0","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}


  Scenario: Create namespaces in cluster for organization 13640230 # features/connector-multitenancy-api.feature:404
    Then the response code should be 202 # features/connector-multitenancy-api.feature:412
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou150 due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou100","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou150 due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou100","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}


  Scenario Outline: Use Admin API to create namespaces for end users # features/connector-multitenancy-api.feature:704
    Then the response code should be 202 # features/connector-multitenancy-api.feature:716
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou14g due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou10g","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou14g due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou10g","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}


  Scenario Outline: Use Admin API to create namespaces for end users # features/connector-multitenancy-api.feature:704
    Then the response code should be 202 # features/connector-multitenancy-api.feature:716
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou0t0 due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0s0","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou0t0 due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0s0","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}


  Scenario Outline: Use Admin API to create namespaces for end users # features/connector-multitenancy-api.feature:704
    Then the response code should be 202 # features/connector-multitenancy-api.feature:716
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou11g due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0tg","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou11g due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0tg","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}


  Scenario: Use Admin API to create namespace for organization 13640231. # features/connector-multitenancy-api.feature:873
    Then the response code should be 202 # features/connector-multitenancy-api.feature:885
      Error: after scenario hook failed: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou160 due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0ug","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
, step error: expected response code to be: 202, but actual is: 500, body: {"reason":"failed to create service account for connector cluster cc72k7e4902vuqsou160 due to error: KAFKAS-MGMT-9: error getting access token\n caused by: failed to get new token from gocloak with error: 400 Bad Request: invalid_client: Invalid client credentials","operation_id":"cc72k7e4902vuqsou0ug","id":"9","kind":"Error","href":"/api/connector_mgmt/v1/errors/9","code":"CONNECTOR-MGMT-9"}
```

**Comment by miguelsorianod** [comment]
> > cc @valdar @dhirajsb @lburgazzoli it seems some connector test/s are failing in this PR. Could you check why?
> > Thanks
> 
> If it helps, the connector tests that are failing seem to be:
> 
> ```
>         --- FAIL: TestFeatures/connector_agent_api/connector_cluster_is_created_and_agent_processes_assigned_a_deployment. (18.12s)
> 
> ...
> 
> --- Failed steps:
> 
>   Scenario: connector cluster is created and agent processes assigned a deployment. # features/connector-agent-api.feature:19
>     Then the response code should be 410 # features/connector-agent-api.feature:1652
>       Error: after scenario hook failed: expected response code to be: 410, but actual is: 200, body: {"id":"cc727du227cqd7lhuo70","kind":"ConnectorNamespace","href":"/api/connector_mgmt/v1/kafka_connector_namespaces/cc727du227cqd7lhuo70","owner":"cc727ce227cqd7lhulv0","created_at":"2022-08-30T14:50:31.729982Z","modified_at":"2022-08-30T14:50:33.058595Z","name":"tender-whippet-namespace","annotations":{"connector_mgmt.bf2.org/profile":"default-profile"},"resource_version":19,"quota":{},"cluster_id":"cc727ce227cqd7lhumag","tenant":{"kind":"organisation","id":"20000000"},"status":{"state":"deleted","version":"0.0.1","connectors_deployed":0}}
> , step error: expected response code to be: 410, but actual is: 200, body: {"id":"cc727du227cqd7lhuo70","kind":"ConnectorNamespace","href":"/api/connector_mgmt/v1/kafka_connector_namespaces/cc727du227cqd7lhuo70","owner":"cc727ce227cqd7lhulv0","created_at":"2022-08-30T14:50:31.729982Z","modified_at":"2022-08-30T14:50:33.058595Z","name":"tender-whippet-namespace","annotations":{"connector_mgmt.bf2.org/profile":"default-profile"},"resource_version":19,"quota":{},"cluster_id":"cc727ce227cqd7lhumag","tenant":{"kind":"organisation","id":"20000000"},"status":{"state":"deleted","version":"0.0.1","connectors_deployed":0}}
> ```

It seems the test pass now after rerunning the testts so I understand it's a flaky test in the connectors test and does not have anything to do with the changes in this PR

**Comment by dhirajsb** [comment]
> It seems the test pass now after rerunning the testts so I understand it's a flaky test in the connectors test and does not have anything to do with the changes in this PR

We have been adding more and more test scenarios and CI also runs kafka tests in parallel. So the 10s timeout we have on some test operations might have become borderline, causing some random test to fail. I'll use another one of my open PRs to bump up the timeout and see if that fixes this.

**Review by dhirajsb — APPROVED** [review]
lgtm

**Review by machi1990 — APPROVED** [review]

**Comment by machi1990** [comment]
@bf2fc6cc711aee1a0c2a/control-plane please take note of this.

@miguelsorianod might be good to send an internal message as well for people to consider bumping their go version once this PR is merged

**Pull request merged**
