### PR TITLE
Included new statuses

### PR DESCRIPTION
**Pull request by HemaHG**
Signed-off-by: hemahg <hhg@redhat.com>

## Description
There are 3 new statuses `suspending`, `suspended`, and `resuming` supported by the backend but not included in the open API. The PR includes the new statues 
## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Comment by HemaHG** [comment]
@pawelpaszki please review the PR

**Comment by pawelpaszki** [comment]
please run `make openapi/generate`. any change in the openapi spec requires this command to be executed to generate other api dependencies

**Review by pawelpaszki — DISMISSED** [review]
there is still one file changed as a result of the api spec change. did you run the `make openapi/generate` and committed all changed files?

**Comment by pawelpaszki** [comment]
the change looks good now. thanks. rebase is required though

**Pull request merged**
