### PR TITLE
fix: replace sed separator with '#'

### PR DESCRIPTION
**Pull request by ziccardi**
## Description

New secrets contain the '/' char, causing sed to fail.

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Review by miguelsorianod — COMMENTED** [review]
I see more than the aws secret access key related code has been changed.

This assumes `#` is a character that cannot appear in any of the elements that have been changed.

Has that  been verified?

**Comment by ziccardi** [comment]
> I see more than the aws secret access key related code has been changed.
> 
> This assumes `#` is a character that cannot appear in any of the elements that have been changed.
> 
> Has that been verified?

AWS account ID: composed by 12 digit 
AWS access Key ID: only characters. See [here](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetAccessKeyInfo.html)
AWS secret access key: (?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=]). (see [here](https://aws.amazon.com/it/blogs/security/a-safer-way-to-distribute-aws-credentials-to-ec2/))
OCM_OFFLINE_TOKEN: concatenated base64 strings - no hash
OBSERVATORIUM= \w{3}_base 64 - no hash

**Review by machi1990 — APPROVED** [review]

**Comment by miguelsorianod** [comment]
:+1: . A note about the AWS access key and private access key is that they offer no guarantee about the set of characters that they will use. They can change it at any moment. But there's not much we can do and it does not seem very likely so we can go ahead with it

**Comment by ziccardi** [comment]
> 👍 . A note about the AWS access key and private access key is that they offer no guarantee about the set of characters that they will use. They can change it at any moment. But there's not much we can do and it does not seem very likely to change so we can go ahead with it

They can of course change the format in the future. Currently, however they say the format is [\w]*:
image

**Comment by miguelsorianod** [comment]
> > +1 . A note about the AWS access key and private access key is that they offer no guarantee about the set of characters that they will use. They can change it at any moment. But there's not much we can do and it does not seem very likely to change so we can go ahead with it
> 
> They can of course change the format in the future. Currently, however they say the format is [\w]*: image

Yes. That's for access key.
For secret access key they don't seem to document it in the API reference

**Pull request merged**
