### PR TITLE
feat: report a user friendly error message on data plane failed states

### PR DESCRIPTION
**Pull request by valeriiashapoval**
## Description
https://issues.redhat.com/browse/MGDSTRM-6982 - report a user friendly error message on data plane failed states

## Checklist (Definition of Done)
- [X] All acceptance criteria specified in JIRA have been completed
- [X] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [X] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Comment by miguelsorianod** [comment]
My understanding is that the issue is that the `FailedReason` attribute of the Kafka request ends up being shown in the UI side, and sometimes we show information that might be sensitive or not really relevant to the end user.
This could be the case when information about a Secret is shown but that's not the only case. For that reason I think the set of changes should be more generic instead of checking a specific error message content.

I would take the approach in the following way:
In the `setKafkaClusterFailed` set `FailedReason` to a literal string like "Kafka <id> status reported as failed from the data plane" and then log with the logger the real error message.

**Comment by miguelsorianod** [comment]
cc @davidffrench to confirm if what I wrote in my previous comment (https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1174#issuecomment-1178847859) matches the expectations of the original issue.
The implication is that the end-user will not see nor be able to see details on why it failed when the data plane reports the kafka with the ready condition to value error

**Comment by miguelsorianod** [comment]
I also observed that in the PR there are several commits but they seem to all be related to the same functionality. Please squash them once the functionality is ready. Thanks.

**Comment by machi1990** [comment]
> My understanding is that the issue is that the `FailedReason` attribute of the Kafka request ends up being shown in the UI side, and sometimes we show information that might be sensitive or not really relevant to the end user. This could be the case when information about a Secret is shown but that's not the only case. For that reason I think the set of changes should be more generic instead of checking a specific error message content.
> 
> I would take the approach in the following way: In the `setKafkaClusterFailed` set `FailedReason` to a literal string like "Kafka status reported as failed from the data plane" and then log with the logger the real error message.

+1

**Comment by machi1990** [comment]
> Thanks @miguelsorianod @machi1990 ! Just added the changes.

Thanks @valeriiashapoval. It seems like the tests are failing for a related change in this PR. Can you have a look?

**Pull request merged**
