### PR TITLE
[DRAFT] MGDCTRS-2034: Remove dbapi.ConnectorDeployment.Annotations

### PR DESCRIPTION
**Pull request by manstis**
**=== DRAFT ===**

Depends on a fix to `gorm`. See https://github.com/go-gorm/gorm/pull/6058

Depends on https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1637/ to upgrade to latest `gorm` libraries.

## Description
See https://issues.redhat.com/browse/MGDCTRS-2034

`dbapi.ConnectorDeployment.Annotations` is not needed. See JIRA for more information.

## Checklist (Definition of Done)
- [x] All acceptance criteria specified in JIRA have been completed
- [x] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- ~[ ] Documentation added for the feature~
- [x] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- ~[ ] Required metrics/dashboards/alerts have been added (or PR created).~
- ~[ ] Required Standard Operating Procedure (SOP) is added.~
- ~[ ] JIRA has been created for changes required on the client side~

### CODE REVIEW

**Comment by manstis** [comment]
I can see why this is failing.. and it highlights why `ConnectorAnnotations` also lives on `ConnectorDeployment`.

When a `Connector` is deleted the `ConnectorDeployment` is left dangling. Retrieval of the _soft-deleted_ `Connector.Annotations` is not that easy with `gorm` (https://github.com/go-gorm/gorm/issues/6054) and use of native SQL has other issues (https://github.com/go-gorm/gorm/issues/6052).

I am investigating a bit more.. but the simple solution is to keep the _hack_ and close this PR.

**Comment by valdar** [comment]
@manstis just reading the error message without any more sophisticated investigation, I would have assumed that gorm still try to load the connectorDeployment -> Annotation relation somehow?

**Comment by manstis** [comment]
> @manstis just reading the error message without any more sophisticated investigation, I would have assumed that gorm still try to load the ConnectorDeployment -> Annotation relation somehow?

Yes, keeping `ConnectorDeployment.Annotations` works around a bug in `gorm` but this PR tries to remove `ConnectorDeployment.Annotations` as it really lives on `ConnectorDeployment.Connector.Annotations` at the database level. i.e. there is no foreign key between `connector_deployments`->`connector_annotations` only between `connector_deployments`->`connectors`->`connector_annotations`. If a FK is added it causes other problems (I encountered when adding support for Smart Event Processors).

When `gorm` runs [this](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/internal/services/connector_cluster.go#L436) for the "dangling" `ConnectorDeployment`'s test it fails to return `Connector` instances as they have been _soft-deleted_. I tried adding `Unscoped()` to the query locally but it is not honoured by the `Preload("Annotations")` and hence zero `Annotations` are returned making the test still fail. I have reported it and provide a fix: https://github.com/go-gorm/gorm/pull/6058.

I'll keep this PR pending.. as when `gorm` is fixed we may be able to upgrade and complete this PR.

**Comment by manstis** [comment]
RHOC has been cancelled.

**Pull request closed without merging**
