### PR TITLE
fix(connectors): fixes MGDCTRS-775, handle namespace agent status update errors, MGDCTRS-776, delete `deleting` namespaces not on data plane

### PR DESCRIPTION
**Pull request by dhirajsb**
## Description
Fixed namespace deletion process for unused and used deleting namespaces.

## Verification Steps
Integration tests for the fixes should pass in CI.

## Checklist (Definition of Done)
- [X] All acceptance criteria specified in JIRA have been completed
- [X] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
~~- [ ] Documentation added for the feature~~
- [x] CI and all relevant tests are passing
- [ ] Code Review completed
~~- [ ] Verified independently by reviewer~~
~~- [ ] Required metrics/dashboards/alerts have been added (or PR created).~~
~~- [ ] Required Standard Operating Procedure (SOP) is added.~~
~~- [ ] JIRA has created for changes required on the client side~~

### CODE REVIEW

**Comment by dhirajsb** [comment]
@lburgazzoli I've added a `deleted` state in namespace, which is set and used by the fleet manager. 
* It checks to see whether an _empty_ `deleting` namespace had any deployments in the past. 
* If it didn't, it sets the namespace state to `deleted` in namespace reconciliation. 
* If the namespace had deployments before being emptied, it waits for the agent to update cluster status without that namespace to indicate that it has been successfully deleted. 
* Namespace reconciliation deletes namespaces with status `deleted`.

Let me know whether I missed anything.

**Comment by lburgazzoli** [comment]
> * It checks to see whether an _empty_ `deleting` namespace had any deployments in the past.
> * If it didn't, it sets the namespace state to `deleted` in namespace reconciliation.

Just for confirmation: will the fleetshard sees namespace in status `deleted` ?

**Comment by dhirajsb** [comment]
Yes, it's theoretically possible that the fleetshard could see a `deleted` namespace. While the status update from agent immediately requests an async namespace reconciliation to get rid of deleted namespaces, it's possible that the agent could simultaneously list namespaces before the actual delete.

**Comment by dhirajsb** [comment]
Actually, on a hunch I had already added a `status_phase` search param for namespaces. So, the agent could also just call the namespace list API with `?search=status_phase<>'deleted'`.

**Comment by dhirajsb** [comment]
@lburgazzoli, @valdar can you approve and merge so we can test it in dev?

**Comment by lburgazzoli** [comment]
LGTM, @valdar can you have a look ?

**Review by valdar — APPROVED** [review]
lgtm

**Pull request merged**
