### PR TITLE
feat: removed additional commands from kfm cli

### PR DESCRIPTION
**Pull request by valeriiashapoval**
## Description
https://issues.redhat.com/browse/MGDSTRM-8980 - Remove additional commands from kfm cli

## Checklist (Definition of Done)

- [X] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [X] CI and all relevant tests are passing
- [x] Code Review completed
- [x] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Comment by pawelpaszki** [comment]
code changes look good to me. Great work again @valeriiashapoval ! Let's wait for another set of eyes to have a look and approve

**Comment by valeriiashapoval** [comment]
> code changes look good to me. Great work again @valeriiashapoval ! Let's wait for another set of eyes to have a look and approve

Thank you @pawelpaszki !

**Comment by miguelsorianod** [comment]
A side comment about style:

I noticed the commit message is written in past tense. I recommend you writing commit messages in imperative present tense. A commit can be seen as a set of changes that are going to be applied when the commit is applied. When writing a commit message think of it as "If applied, this commit will ..."

For example, instead of a commit message:
`feat: removed additional commands from kfm cli`

have it as:
`feat: remove additional commands from kfm cli`

That way of writing message commits is also used and recommended by the `git` project itself:
https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches

**Comment by valeriiashapoval** [comment]
> A side comment about style:
> 
> I noticed the commit message is written in past tense. I recommend you writing commit messages in imperative present tense. A commit can be seen as a set of changes that are going to be applied when the commit is applied. When writing a commit message think of it as "If applied, this commit will ..."
> 
> For example, instead of a commit message: `feat: removed additional commands from kfm cli`
> 
> have it as: `feat: remove additional commands from kfm cli`
> 
> That way of writing message commits is also used and recommended by the `git` project itself (see `[[imperative-mood]]` section): https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches

Thank you @miguelsorianod for pointing it out!

**Review by machi1990 — APPROVED** [review]

**Comment by valeriiashapoval** [comment]
> Thanks for this @valeriiashapoval! Looks good to me

Thank you @JameelB!

**Pull request merged**
