### PR TITLE
feat: remove fields deprecated as part of supporting larger kafka instances

### PR DESCRIPTION
**Pull request by JameelB**
## Description
Removes the following deprecated fields:
- **/api​/kafkas_mgmt​/v1​/cloud_providers​/{id}​/regions**
   - instance_type (query parameter): Removed as it is not used
   - max_capacity_reached (from RegionCapacityListItem schema): Replaced by _available_sizes_ in the same schema.
   - supported_instance_types (from CloudRegionList schema): Duplicated information of _capacity_ in the same schema.
- **/api/kafkas_mgmt/v1/kafkas**
  - multi_az (from KafkaRequestPayload schema): No longer used, this is now determined based on the Kafka request 'plan' attribute.

Related PRs:
- https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/859
- https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/965

## Verification Steps
* Code review
* Ensure all CI checks are passing

## Checklist (Definition of Done)

- [x] All acceptance criteria specified in JIRA have been completed
- [x] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] ~~Documentation added for the feature~~
- [ ] ~~Required metrics/dashboards/alerts have been added (or PR created).~~
- [ ] ~~Required Standard Operating Procedure (SOP) is added.~~
- [ ] ~~JIRA has been created for changes required on the client side~~

### CODE REVIEW

**Comment by JameelB** [comment]
@riccardo-forina @wtrocki fyi

**Review by machi1990 — APPROVED** [review]
code change looks good.

**Comment by JameelB** [comment]
Thanks for the review and confirmation @dimakis. Will merge changes once ci passes.

**Pull request merged**
