### PR TITLE
feat: bump Observability Operator version to v4.0.1

### PR DESCRIPTION
**Pull request by vmanley**
## Description

Bump version of Observability Operator to v4.0.1

## Checklist (Definition of Done)

- [ ] ~~All acceptance criteria specified in JIRA have been completed~~
- [ ] ~~Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)~~
- [ ] ~~Documentation added for the feature~~
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] ~~Required metrics/dashboards/alerts have been added (or PR created).~~
- [ ] ~~Required Standard Operating Procedure (SOP) is added.~~
- [ ] ~~JIRA has been created for changes required on the client side~~

### CODE REVIEW

**Review by machi1990 — COMMENTED** [review]
Thanks.

The change lgtm to me, has this been verified?

When this is merged, can you bump kas-installer just like in https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/pull/252 and then we'll need @MikeEdgar to create a new version of kas-installer after the PR is merged.

**Review by machi1990 — APPROVED** [review]

**Comment by vmanley** [comment]
@machi1990 Just verifying now

**Comment by vmanley** [comment]
Verified on cluster

**Review by pb82 — APPROVED** [review]

**Comment by machi1990** [comment]
Thanks @vmanley merging this now. Let's follow up with creating an PR against kas-installer.

**Pull request merged**
