### PR TITLE
fix(connectors): MGDCTRS-494 fix Missing deployment inconsistency by recreating them during reconcile if they are missing.

### PR DESCRIPTION
**Pull request by valdar**
## Description

If a connector deployment is missing for  whatever reason during the lifecycle of a connector, that connector become stuck and can not be acted upon. If we detect such  scenario during reconciliation, we create the deployments again.

## Checklist (Definition of Done)

- [x] All acceptance criteria specified in JIRA have been completed
- [x] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [x] ~~Documentation added for the feature~~
- [x] CI and all relevant tests are passing
- [x] Code Review completed
- [x] Verified independently by reviewer
- [x] ~~Required metrics/dashboards/alerts have been added (or PR created).~~
- [x] ~~Required Standard Operating Procedure (SOP) is added.~~
- [x] ~~JIRA has created for changes required on the client side~~

### CODE REVIEW

**Review by lburgazzoli — APPROVED** [review]

**Comment by dhirajsb** [comment]
@valdar did you figure out why this is happening? AFAICT, deployments are only deleted in two places:
* on startup to clean any deployments that don't have connectors
* when agent sends back a `deleted` status for a connector deployment status update
I get that the integration test deletes the deployment directly in the DB to create this condition. But what's causing a deployment to disappear in a running live fleet manager? 
Without that root cause analysis, I suspect the fleet manager is just going to go in a cycle deleting and then restoring deployments.

**Comment by valdar** [comment]
> @valdar did you figure out why this is happening? AFAICT, deployments are only deleted in two places:
> 
>     * on startup to clean any deployments that don't have connectors
> 
>     * when agent sends back a `deleted` status for a connector deployment status update
> 
> 
> I get that the integration test deletes the deployment directly in the DB to create this condition. But what's causing a deployment to disappear in a running live fleet manager? Without that root cause analysis, I suspect the fleet manager is just going to go in a cycle deleting and then restoring deployments.

I admit that the analysis was all theoretical since we observed the connectors in those states but we have yet no mean to better investigate how they get there since read only query service is still not in place. A possible explanation is that between lines https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/internal/services/connector_cluster.go#L499 and https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/internal/services/connector_cluster.go#L505 something happen preventing line 505 to be executed, for instance:

- a concurrent change in desired state 
- k8s decided to bounce the pod
- we bounced it by issuing a deployment 

in that case the connectors could end up in the state they are stuck in.

**Comment by dhirajsb** [comment]
That's a good hypothesis. I am assuming you will be able to try this change before the multitenancy PR is merged. Can you also change the reconcile loop at:
```
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/internal/workers/connector_mgr.go#L141 
to accumulate errors like in line:
https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/internal/workers/connector_mgr.go#L119
```
That would make it so that one failing connector doesn't stop other connectors from reconciling.

**Comment by valdar** [comment]
> That's a good hypothesis. I am assuming you will be able to try this change before the multitenancy PR is merged. 

That is the idea yes, to first merge this one and release. Then review and merge multitenancy to be released next Thursday.

> Can you also change the reconcile loop at:
> ```
> https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/internal/workers/connector_mgr.go#L141 
> to accumulate errors like in line:
> https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/connector/internal/workers/connector_mgr.go#L119
> ```
> 
> That would make it so that one failing connector doesn't stop other connectors from reconciling.

I think I have done it.

**Pull request merged**
