### PR TITLE
build(dockerfile): ensure that docker in installed so that commitsha is read during build

### PR DESCRIPTION
**Pull request by machi1990**
This follows up on https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1321, notably https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1321#issuecomment-1263717395

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Review by miguelsorianod — APPROVED** [review]

**Comment by miguelsorianod** [comment]
Do we need that in any other image/environment? @machi1990

**Comment by miguelsorianod** [comment]
This is very surprising behavior as I all found in the Go documentation is:
```
Version control information is embedded if the go command is invoked in a directory within a Git, Mercurial, Fossil, or Bazaar repository, and the main package and its containing main module are in the same repository. 
```

**Comment by machi1990** [comment]
> This is very surprising behavior as all I found in the Go documentation is:
> 
> ```
> Version control information is embedded if the go command is invoked in a directory within a Git, Mercurial, Fossil, or Bazaar repository, and the main package and its containing main module are in the same repository. 
> ```
> 
> Which does not mention the need of having `git` installed

Yes, I think the documentation could have been better on that regard. 
Now everything relies on the assumption that users can make when reading ..`"Version control information is embedded if the go command is invoked in a directory within a Git, Mercurial, Fossil, or Bazaar repository"` that if you are in a vcs repo, then you must have a corresponding vcs tool installed.

The requirement of having git initially caused some issues e.g https://github.com/golang/go/issues/51723

**Pull request merged**
