### PR TITLE
chore: Remove Owner field from KFM Service account API spec

### PR DESCRIPTION
**Pull request by JasonPowr**
## Description
The Owner field in the Service account API spec has been marked for deprecation. An email has been sent out notifying people of this deprecation. It needs to be fully removed from the code.

Jira: [Here](https://issues.redhat.com/browse/MGDSTRM-7913)

## Verification Steps
1. Run `make run/docs`
2. Can see that in the Service account endpoints the Owner field is no longer returned.

## Checklist (Definition of Done)

- [x] All acceptance criteria specified in JIRA have been completed
- [ ] ~~Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)~~
- [ ] ~~Documentation added for the feature~~
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] ~~Required metrics/dashboards/alerts have been added (or PR created).~~
- [ ] ~~Required Standard Operating Procedure (SOP) is added.~~
- [ ] ~~JIRA has been created for changes required on the client side~~

### CODE REVIEW

**Comment by JasonPowr** [comment]
Hey @wtrocki @riccardo-forina Just wondering before this pr is merged is this field still being used by the UI and CLI

**Comment by wtrocki** [comment]
@JasonPowr I will check that for you (need 1-2 days). Generally there could be some risk of breaking clients, automation etc. 
Need to learn more about this change and speak with the team first.

**Comment by JasonPowr** [comment]
> @JasonPowr I will check that for you (need 1-2 days). Generally there could be some risk of breaking clients, automation etc. Need to learn more about this change and speak with the team first.

No problem at all :)

**Comment by JasonPowr** [comment]
Closing this pr as it has been decided to keep the owner field for now. :)

**Pull request closed without merging**
