### PR TITLE
feat(clusters): add a flag to enable disable configuration of identity provider

### PR DESCRIPTION
**Pull request by machi1990**
## Description

Closes https://issues.redhat.com/browse/MGDSTRM-8384. Follows up on
https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/pull/163#discussion_r862037539

## Verification Steps

- Added unit tests should pass
- Verification from @MikeEdgar in kas-installer that: (1) The identity provider is disabled when the flag `ENABLE_KAFKA_SRE_IDENTITY_PROVIDER_CONFIGURATION` is set to `false`. (2). When the parameter is removed or set to `true` identity provider configuration is enabled

This should not have any impact on our deployments environment as the `ENABLE_KAFKA_SRE_IDENTITY_PROVIDER_CONFIGURATION` is enabled by default.

## Checklist (Definition of Done)

- [x] All acceptance criteria specified in JIRA have been completed
- [x] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [x] Documentation added for the feature
- [x] CI and all relevant tests are passing
- [x] Code Review completed
- [ ] Verified independently by reviewer
- ~~[ ] Required metrics/dashboards/alerts have been added (or PR created).~~
- ~~[ ] Required Standard Operating Procedure (SOP) is added.~~
- ~~[ ] JIRA has created for changes required on the client side~~

### CODE REVIEW

**Review by JameelB — COMMENTED** [review]
changes looks good to me, waiting on verification from @MikeEdgar

**Review by MikeEdgar — APPROVED** [review]
Works for me in kas-installer using the OCM provider :+1:

**Comment by machi1990** [comment]
Thanks @MikeEdgar 

@JameelB can you have a look too?

**Review by JameelB — APPROVED** [review]
Thanks for this @machi1990!

**Pull request merged**
