### PR TITLE
feat: bump kas fleet manager api and private admin api openapi versions

### PR DESCRIPTION
**Pull request by miguelsorianod**
## Description

Related to https://issues.redhat.com/browse/MGDSTRM-8304.

The changes are the following
* Bump version for the openapi/kas-fleet-manager.yaml from 1.4.0 to 1.5.0: Multiple backward-compatible changes have been performed
* Bump version for the openapi/kas-fleet-manager-private-admin.yaml from 0.0.2 to 0.0.3: Addition of a new size_id field for the `Kafka` schema

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has created for changes required on the client side

### CODE REVIEW

**Review by pb82 — APPROVED** [review]
LGTM. No verification needed since all changes are version bump related.

**Comment by machi1990** [comment]
Is there a reason why we are not bumping the agents openapi spec as well https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/30e785f94092c3e7e023ce7e97e672248ca21381/openapi/kas-fleet-manager-private.yaml? Or it was already bumped?

**Comment by miguelsorianod** [comment]
> Is there a reason why we are not bumping the agents openapi spec as well https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/30e785f94092c3e7e023ce7e97e672248ca21381/openapi/kas-fleet-manager-private.yaml? Or it was already bumped?

It was already bumped

**Comment by machi1990** [comment]
Thanks!

**Pull request merged**
