### PR TITLE
chore: deprecate quota_type from supported instance types endpoint

### PR DESCRIPTION
**Pull request by miguelsorianod**
## Description

Related to https://issues.redhat.com/browse/MGDSTRM-10022.

Due to recent changes billing models specification (https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1371, https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1379) the `quota_type` attribute returned in the `/api/kafkas_mgmt/v1/instance_types/{cloud_provider}/{cloud_region}` is not used anymore and it will not reflect the real state of the supported quota type(s).

This PR takes care of:
* Marking the `quota_type` attribute in the `/api/kafkas_mgmt/v1/instance_types/{cloud_provider}/{cloud_region}` response as deprecated
* Renaming go types corresponding to that attribute with the `Deprecated` prefix
* Renaming go types corresponding to that attribute at kafka supported instance types configuration level (`config/kafka-instance-types-configuration.yaml`) with the Deprecated prefix

This PR only marks the field as deprecated. It is still returned as part of the endpoint response and available in the kafka supported instance types configuration (to support returning it as part of the endpoint). Once the deprecation period finishes then we should implement the removal from both the endpoint and the configuration file.

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA have been completed
- [ ] Unit and integration tests added that prove the fix is effective or the feature works (tested against emulated and non-emulated OCM environment)
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer
- [ ] All PR comments are resolved either by addressing them or creating follow up tasks
- [ ] Required metrics/dashboards/alerts have been added (or PR created).
- [ ] Required Standard Operating Procedure (SOP) is added.
- [ ] JIRA has been created for changes required on the client side

### CODE REVIEW

**Comment by miguelsorianod** [comment]
cc @dimakis as we commented through other channels

**Review by ziccardi — COMMENTED** [review]
LGTM. I will leave to @dimakis the latst word on this

**Comment by dimakis** [comment]
I've had a look and Rama has had a look over this too. Neither of us sees this attribute being used in the CLI. 
LGTM

**Comment by miguelsorianod** [comment]
Thank you @dimakis :+1: we will proceed with the deprecation of the attribute then

**Review by JameelB — APPROVED** [review]

**Pull request merged**
